export enum Roles{
    ADMIN = 'ADMIN',
    SUPERADMIN = 'SUPERADMIN',
    BRANCHMANAGER = 'BRANCHMANAGER',
    COORDINATOR = 'COORDINATOR',
    RECEPTIONIST = 'RECEPTIONIST',
    ACCOUNTANT = 'ACCOUNTANT',
    ARTIST = 'RECEPTIONIST',
    ARTISTMANAGER ='RECEPTIONIST',
    TABLE = 'MANAGER'


}